apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  ports:
    - port: 8901
      protocol: TCP
      targetPort: 8901
  selector:
    app: catalog
  sessionAffinity: None
  type: ClusterIP