apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : personal
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: personal
  source:
    path   : "application/personal-account-service"
    repoURL: "git@github.com:02ten/marketplace-k8s-config.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true    