apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: personal
  name: personal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal
  template:
    metadata:
      labels:
        app: personal
    spec:
      containers:
        - image: 02ten/marketplace-personal-account:ae8780677977a05add3a14fd912ded32ece76bdd
          imagePullPolicy: Always
          name: personal
          resources:
            limits:
              cpu: "0.5"
              memory: "500M"
      dnsPolicy: ClusterFirst
      restartPolicy: Always