apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: personal-account
  name: personal-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-account
  template:
    metadata:
      labels:
        app: personal-account
    spec:
      containers:
        - image: 02ten/marketplace-personal-account:643aba2c1cf996c6843eb2205be606b98c52938d
          imagePullPolicy: Always
          name: personal-account
          resources:
            limits:
              cpu: "0.5"
              memory: "500M"
      dnsPolicy: ClusterFirst
      restartPolicy: Always