apiVersion: v1
kind: Service
metadata:
  labels:
    app: personal
  name: personal
spec:
  ports:
    - port: 8902
      protocol: TCP
      targetPort: 8902
  selector:
    app: personal
  sessionAffinity: None
  type: ClusterIP