apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: 02ten/marketplace-auth:ee6e300121b91689e6eaebf32e1b3705dae24978
          imagePullPolicy: Always
          name: auth
          resources:
            limits:
              cpu: "0.5"
              memory: "500M"
      dnsPolicy: ClusterFirst
      restartPolicy: Always