apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
        - name: krakend
          image: 02ten/marketplace-krakend:1.0.20
          imagePullPolicy: Always
